'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace wscdc
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceSoap", [Namespace]:="http://servicios1.afip.gob.ar/wscdc/")>  _
    Partial Public Class Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ComprobantesModalidadConsultarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ComprobantesTipoConsultarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DocumentosTipoConsultarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private OpcionalesTipoConsultarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ComprobanteConstatarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ComprobanteDummyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Principal.My.MySettings.Default.Principal_wscdc_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ComprobantesModalidadConsultarCompleted As ComprobantesModalidadConsultarCompletedEventHandler
        
        '''<remarks/>
        Public Event ComprobantesTipoConsultarCompleted As ComprobantesTipoConsultarCompletedEventHandler
        
        '''<remarks/>
        Public Event DocumentosTipoConsultarCompleted As DocumentosTipoConsultarCompletedEventHandler
        
        '''<remarks/>
        Public Event OpcionalesTipoConsultarCompleted As OpcionalesTipoConsultarCompletedEventHandler
        
        '''<remarks/>
        Public Event ComprobanteConstatarCompleted As ComprobanteConstatarCompletedEventHandler
        
        '''<remarks/>
        Public Event ComprobanteDummyCompleted As ComprobanteDummyCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios1.afip.gob.ar/wscdc/ComprobantesModalidadConsultar", RequestNamespace:="http://servicios1.afip.gob.ar/wscdc/", ResponseNamespace:="http://servicios1.afip.gob.ar/wscdc/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ComprobantesModalidadConsultar(ByVal Auth As CmpAuthRequest) As FacModTipoResponse
            Dim results() As Object = Me.Invoke("ComprobantesModalidadConsultar", New Object() {Auth})
            Return CType(results(0),FacModTipoResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ComprobantesModalidadConsultarAsync(ByVal Auth As CmpAuthRequest)
            Me.ComprobantesModalidadConsultarAsync(Auth, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ComprobantesModalidadConsultarAsync(ByVal Auth As CmpAuthRequest, ByVal userState As Object)
            If (Me.ComprobantesModalidadConsultarOperationCompleted Is Nothing) Then
                Me.ComprobantesModalidadConsultarOperationCompleted = AddressOf Me.OnComprobantesModalidadConsultarOperationCompleted
            End If
            Me.InvokeAsync("ComprobantesModalidadConsultar", New Object() {Auth}, Me.ComprobantesModalidadConsultarOperationCompleted, userState)
        End Sub
        
        Private Sub OnComprobantesModalidadConsultarOperationCompleted(ByVal arg As Object)
            If (Not (Me.ComprobantesModalidadConsultarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ComprobantesModalidadConsultarCompleted(Me, New ComprobantesModalidadConsultarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios1.afip.gob.ar/wscdc/ComprobantesTipoConsultar", RequestNamespace:="http://servicios1.afip.gob.ar/wscdc/", ResponseNamespace:="http://servicios1.afip.gob.ar/wscdc/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ComprobantesTipoConsultar(ByVal Auth As CmpAuthRequest) As CbteTipoResponse
            Dim results() As Object = Me.Invoke("ComprobantesTipoConsultar", New Object() {Auth})
            Return CType(results(0),CbteTipoResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ComprobantesTipoConsultarAsync(ByVal Auth As CmpAuthRequest)
            Me.ComprobantesTipoConsultarAsync(Auth, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ComprobantesTipoConsultarAsync(ByVal Auth As CmpAuthRequest, ByVal userState As Object)
            If (Me.ComprobantesTipoConsultarOperationCompleted Is Nothing) Then
                Me.ComprobantesTipoConsultarOperationCompleted = AddressOf Me.OnComprobantesTipoConsultarOperationCompleted
            End If
            Me.InvokeAsync("ComprobantesTipoConsultar", New Object() {Auth}, Me.ComprobantesTipoConsultarOperationCompleted, userState)
        End Sub
        
        Private Sub OnComprobantesTipoConsultarOperationCompleted(ByVal arg As Object)
            If (Not (Me.ComprobantesTipoConsultarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ComprobantesTipoConsultarCompleted(Me, New ComprobantesTipoConsultarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios1.afip.gob.ar/wscdc/DocumentosTipoConsultar", RequestNamespace:="http://servicios1.afip.gob.ar/wscdc/", ResponseNamespace:="http://servicios1.afip.gob.ar/wscdc/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DocumentosTipoConsultar(ByVal Auth As CmpAuthRequest) As DocTipoResponse
            Dim results() As Object = Me.Invoke("DocumentosTipoConsultar", New Object() {Auth})
            Return CType(results(0),DocTipoResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DocumentosTipoConsultarAsync(ByVal Auth As CmpAuthRequest)
            Me.DocumentosTipoConsultarAsync(Auth, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DocumentosTipoConsultarAsync(ByVal Auth As CmpAuthRequest, ByVal userState As Object)
            If (Me.DocumentosTipoConsultarOperationCompleted Is Nothing) Then
                Me.DocumentosTipoConsultarOperationCompleted = AddressOf Me.OnDocumentosTipoConsultarOperationCompleted
            End If
            Me.InvokeAsync("DocumentosTipoConsultar", New Object() {Auth}, Me.DocumentosTipoConsultarOperationCompleted, userState)
        End Sub
        
        Private Sub OnDocumentosTipoConsultarOperationCompleted(ByVal arg As Object)
            If (Not (Me.DocumentosTipoConsultarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DocumentosTipoConsultarCompleted(Me, New DocumentosTipoConsultarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios1.afip.gob.ar/wscdc/OpcionalesTipoConsultar", RequestNamespace:="http://servicios1.afip.gob.ar/wscdc/", ResponseNamespace:="http://servicios1.afip.gob.ar/wscdc/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function OpcionalesTipoConsultar(ByVal Auth As CmpAuthRequest) As OpcionalTipoResponse
            Dim results() As Object = Me.Invoke("OpcionalesTipoConsultar", New Object() {Auth})
            Return CType(results(0),OpcionalTipoResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub OpcionalesTipoConsultarAsync(ByVal Auth As CmpAuthRequest)
            Me.OpcionalesTipoConsultarAsync(Auth, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub OpcionalesTipoConsultarAsync(ByVal Auth As CmpAuthRequest, ByVal userState As Object)
            If (Me.OpcionalesTipoConsultarOperationCompleted Is Nothing) Then
                Me.OpcionalesTipoConsultarOperationCompleted = AddressOf Me.OnOpcionalesTipoConsultarOperationCompleted
            End If
            Me.InvokeAsync("OpcionalesTipoConsultar", New Object() {Auth}, Me.OpcionalesTipoConsultarOperationCompleted, userState)
        End Sub
        
        Private Sub OnOpcionalesTipoConsultarOperationCompleted(ByVal arg As Object)
            If (Not (Me.OpcionalesTipoConsultarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent OpcionalesTipoConsultarCompleted(Me, New OpcionalesTipoConsultarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios1.afip.gob.ar/wscdc/ComprobanteConstatar", RequestNamespace:="http://servicios1.afip.gob.ar/wscdc/", ResponseNamespace:="http://servicios1.afip.gob.ar/wscdc/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ComprobanteConstatar(ByVal Auth As CmpAuthRequest, ByVal CmpReq As CmpDatos) As CmpResponse
            Dim results() As Object = Me.Invoke("ComprobanteConstatar", New Object() {Auth, CmpReq})
            Return CType(results(0),CmpResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ComprobanteConstatarAsync(ByVal Auth As CmpAuthRequest, ByVal CmpReq As CmpDatos)
            Me.ComprobanteConstatarAsync(Auth, CmpReq, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ComprobanteConstatarAsync(ByVal Auth As CmpAuthRequest, ByVal CmpReq As CmpDatos, ByVal userState As Object)
            If (Me.ComprobanteConstatarOperationCompleted Is Nothing) Then
                Me.ComprobanteConstatarOperationCompleted = AddressOf Me.OnComprobanteConstatarOperationCompleted
            End If
            Me.InvokeAsync("ComprobanteConstatar", New Object() {Auth, CmpReq}, Me.ComprobanteConstatarOperationCompleted, userState)
        End Sub
        
        Private Sub OnComprobanteConstatarOperationCompleted(ByVal arg As Object)
            If (Not (Me.ComprobanteConstatarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ComprobanteConstatarCompleted(Me, New ComprobanteConstatarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios1.afip.gob.ar/wscdc/ComprobanteDummy", RequestNamespace:="http://servicios1.afip.gob.ar/wscdc/", ResponseNamespace:="http://servicios1.afip.gob.ar/wscdc/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ComprobanteDummy() As DummyResponse
            Dim results() As Object = Me.Invoke("ComprobanteDummy", New Object(-1) {})
            Return CType(results(0),DummyResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ComprobanteDummyAsync()
            Me.ComprobanteDummyAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ComprobanteDummyAsync(ByVal userState As Object)
            If (Me.ComprobanteDummyOperationCompleted Is Nothing) Then
                Me.ComprobanteDummyOperationCompleted = AddressOf Me.OnComprobanteDummyOperationCompleted
            End If
            Me.InvokeAsync("ComprobanteDummy", New Object(-1) {}, Me.ComprobanteDummyOperationCompleted, userState)
        End Sub
        
        Private Sub OnComprobanteDummyOperationCompleted(ByVal arg As Object)
            If (Not (Me.ComprobanteDummyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ComprobanteDummyCompleted(Me, New ComprobanteDummyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://servicios1.afip.gob.ar/wscdc/")>  _
    Partial Public Class CmpAuthRequest
        
        Private tokenField As String
        
        Private signField As String
        
        Private cuitField As Long
        
        '''<remarks/>
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Sign() As String
            Get
                Return Me.signField
            End Get
            Set
                Me.signField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cuit() As Long
            Get
                Return Me.cuitField
            End Get
            Set
                Me.cuitField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://servicios1.afip.gob.ar/wscdc/")>  _
    Partial Public Class DummyResponse
        
        Private appServerField As String
        
        Private dbServerField As String
        
        Private authServerField As String
        
        '''<remarks/>
        Public Property AppServer() As String
            Get
                Return Me.appServerField
            End Get
            Set
                Me.appServerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DbServer() As String
            Get
                Return Me.dbServerField
            End Get
            Set
                Me.dbServerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AuthServer() As String
            Get
                Return Me.authServerField
            End Get
            Set
                Me.authServerField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://servicios1.afip.gob.ar/wscdc/")>  _
    Partial Public Class Obs
        
        Private codeField As Integer
        
        Private msgField As String
        
        '''<remarks/>
        Public Property Code() As Integer
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Msg() As String
            Get
                Return Me.msgField
            End Get
            Set
                Me.msgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://servicios1.afip.gob.ar/wscdc/")>  _
    Partial Public Class CmpResponse
        
        Private cmpRespField As CmpDatos
        
        Private resultadoField As String
        
        Private observacionesField() As Obs
        
        Private fchProcesoField As String
        
        Private eventsField() As Evt
        
        Private errorsField() As Err
        
        '''<remarks/>
        Public Property CmpResp() As CmpDatos
            Get
                Return Me.cmpRespField
            End Get
            Set
                Me.cmpRespField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Resultado() As String
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Observaciones() As Obs()
            Get
                Return Me.observacionesField
            End Get
            Set
                Me.observacionesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FchProceso() As String
            Get
                Return Me.fchProcesoField
            End Get
            Set
                Me.fchProcesoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Events() As Evt()
            Get
                Return Me.eventsField
            End Get
            Set
                Me.eventsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Errors() As Err()
            Get
                Return Me.errorsField
            End Get
            Set
                Me.errorsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://servicios1.afip.gob.ar/wscdc/")>  _
    Partial Public Class CmpDatos
        
        Private cbteModoField As String
        
        Private cuitEmisorField As Long
        
        Private ptoVtaField As Integer
        
        Private cbteTipoField As Integer
        
        Private cbteNroField As Long
        
        Private cbteFchField As String
        
        Private impTotalField As Double
        
        Private codAutorizacionField As String
        
        Private docTipoReceptorField As String
        
        Private docNroReceptorField As String
        
        Private opcionalesField() As Opcional
        
        '''<remarks/>
        Public Property CbteModo() As String
            Get
                Return Me.cbteModoField
            End Get
            Set
                Me.cbteModoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CuitEmisor() As Long
            Get
                Return Me.cuitEmisorField
            End Get
            Set
                Me.cuitEmisorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PtoVta() As Integer
            Get
                Return Me.ptoVtaField
            End Get
            Set
                Me.ptoVtaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CbteTipo() As Integer
            Get
                Return Me.cbteTipoField
            End Get
            Set
                Me.cbteTipoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CbteNro() As Long
            Get
                Return Me.cbteNroField
            End Get
            Set
                Me.cbteNroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CbteFch() As String
            Get
                Return Me.cbteFchField
            End Get
            Set
                Me.cbteFchField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImpTotal() As Double
            Get
                Return Me.impTotalField
            End Get
            Set
                Me.impTotalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodAutorizacion() As String
            Get
                Return Me.codAutorizacionField
            End Get
            Set
                Me.codAutorizacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DocTipoReceptor() As String
            Get
                Return Me.docTipoReceptorField
            End Get
            Set
                Me.docTipoReceptorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DocNroReceptor() As String
            Get
                Return Me.docNroReceptorField
            End Get
            Set
                Me.docNroReceptorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Opcionales() As Opcional()
            Get
                Return Me.opcionalesField
            End Get
            Set
                Me.opcionalesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://servicios1.afip.gob.ar/wscdc/")>  _
    Partial Public Class Opcional
        
        Private idField As String
        
        Private valorField As String
        
        '''<remarks/>
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Valor() As String
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://servicios1.afip.gob.ar/wscdc/")>  _
    Partial Public Class Evt
        
        Private codeField As Integer
        
        Private msgField As String
        
        '''<remarks/>
        Public Property Code() As Integer
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Msg() As String
            Get
                Return Me.msgField
            End Get
            Set
                Me.msgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://servicios1.afip.gob.ar/wscdc/")>  _
    Partial Public Class Err
        
        Private codeField As Integer
        
        Private msgField As String
        
        '''<remarks/>
        Public Property Code() As Integer
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Msg() As String
            Get
                Return Me.msgField
            End Get
            Set
                Me.msgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://servicios1.afip.gob.ar/wscdc/")>  _
    Partial Public Class OpcionalTipo
        
        Private idField As String
        
        Private descField As String
        
        '''<remarks/>
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Desc() As String
            Get
                Return Me.descField
            End Get
            Set
                Me.descField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://servicios1.afip.gob.ar/wscdc/")>  _
    Partial Public Class OpcionalTipoResponse
        
        Private resultGetField() As OpcionalTipo
        
        Private errorsField() As Err
        
        Private eventsField() As Evt
        
        '''<remarks/>
        Public Property ResultGet() As OpcionalTipo()
            Get
                Return Me.resultGetField
            End Get
            Set
                Me.resultGetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Errors() As Err()
            Get
                Return Me.errorsField
            End Get
            Set
                Me.errorsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Events() As Evt()
            Get
                Return Me.eventsField
            End Get
            Set
                Me.eventsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://servicios1.afip.gob.ar/wscdc/")>  _
    Partial Public Class DocTipo
        
        Private idField As String
        
        Private descField As String
        
        '''<remarks/>
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Desc() As String
            Get
                Return Me.descField
            End Get
            Set
                Me.descField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://servicios1.afip.gob.ar/wscdc/")>  _
    Partial Public Class DocTipoResponse
        
        Private resultGetField() As DocTipo
        
        Private errorsField() As Err
        
        Private eventsField() As Evt
        
        '''<remarks/>
        Public Property ResultGet() As DocTipo()
            Get
                Return Me.resultGetField
            End Get
            Set
                Me.resultGetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Errors() As Err()
            Get
                Return Me.errorsField
            End Get
            Set
                Me.errorsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Events() As Evt()
            Get
                Return Me.eventsField
            End Get
            Set
                Me.eventsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://servicios1.afip.gob.ar/wscdc/")>  _
    Partial Public Class CbteTipo
        
        Private idField As Integer
        
        Private descField As String
        
        '''<remarks/>
        Public Property Id() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Desc() As String
            Get
                Return Me.descField
            End Get
            Set
                Me.descField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://servicios1.afip.gob.ar/wscdc/")>  _
    Partial Public Class CbteTipoResponse
        
        Private resultGetField() As CbteTipo
        
        Private errorsField() As Err
        
        Private eventsField() As Evt
        
        '''<remarks/>
        Public Property ResultGet() As CbteTipo()
            Get
                Return Me.resultGetField
            End Get
            Set
                Me.resultGetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Errors() As Err()
            Get
                Return Me.errorsField
            End Get
            Set
                Me.errorsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Events() As Evt()
            Get
                Return Me.eventsField
            End Get
            Set
                Me.eventsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://servicios1.afip.gob.ar/wscdc/")>  _
    Partial Public Class FacModTipo
        
        Private codField As String
        
        Private descField As String
        
        Private fchDesdeField As String
        
        Private fchHastaField As String
        
        '''<remarks/>
        Public Property Cod() As String
            Get
                Return Me.codField
            End Get
            Set
                Me.codField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Desc() As String
            Get
                Return Me.descField
            End Get
            Set
                Me.descField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FchDesde() As String
            Get
                Return Me.fchDesdeField
            End Get
            Set
                Me.fchDesdeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FchHasta() As String
            Get
                Return Me.fchHastaField
            End Get
            Set
                Me.fchHastaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://servicios1.afip.gob.ar/wscdc/")>  _
    Partial Public Class FacModTipoResponse
        
        Private resultGetField() As FacModTipo
        
        Private errorsField() As Err
        
        Private eventsField() As Evt
        
        '''<remarks/>
        Public Property ResultGet() As FacModTipo()
            Get
                Return Me.resultGetField
            End Get
            Set
                Me.resultGetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Errors() As Err()
            Get
                Return Me.errorsField
            End Get
            Set
                Me.errorsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Events() As Evt()
            Get
                Return Me.eventsField
            End Get
            Set
                Me.eventsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub ComprobantesModalidadConsultarCompletedEventHandler(ByVal sender As Object, ByVal e As ComprobantesModalidadConsultarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ComprobantesModalidadConsultarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As FacModTipoResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),FacModTipoResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub ComprobantesTipoConsultarCompletedEventHandler(ByVal sender As Object, ByVal e As ComprobantesTipoConsultarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ComprobantesTipoConsultarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CbteTipoResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CbteTipoResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub DocumentosTipoConsultarCompletedEventHandler(ByVal sender As Object, ByVal e As DocumentosTipoConsultarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DocumentosTipoConsultarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DocTipoResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DocTipoResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub OpcionalesTipoConsultarCompletedEventHandler(ByVal sender As Object, ByVal e As OpcionalesTipoConsultarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class OpcionalesTipoConsultarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OpcionalTipoResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OpcionalTipoResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub ComprobanteConstatarCompletedEventHandler(ByVal sender As Object, ByVal e As ComprobanteConstatarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ComprobanteConstatarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CmpResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CmpResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub ComprobanteDummyCompletedEventHandler(ByVal sender As Object, ByVal e As ComprobanteDummyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ComprobanteDummyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DummyResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DummyResponse)
            End Get
        End Property
    End Class
End Namespace
