'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property BackgroundColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("BackgroundColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("BackgroundColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BackgroundImage() As String
            Get
                Return CType(Me("BackgroundImage"),String)
            End Get
            Set
                Me("BackgroundImage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CodigoSucursal() As Integer
            Get
                Return CType(Me("CodigoSucursal"),Integer)
            End Get
            Set
                Me("CodigoSucursal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("c:\reportes")>  _
        Public Property RutaReportes() As String
            Get
                Return CType(Me("RutaReportes"),String)
            End Get
            Set
                Me("RutaReportes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Santa Fe")>  _
        Public Property ProvinciaDefault() As String
            Get
                Return CType(Me("ProvinciaDefault"),String)
            End Get
            Set
                Me("ProvinciaDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("96")>  _
        Public Property DocumentoDefault() As UInteger
            Get
                Return CType(Me("DocumentoDefault"),UInteger)
            End Get
            Set
                Me("DocumentoDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property ResponsabilidadDefault() As UInteger
            Get
                Return CType(Me("ResponsabilidadDefault"),UInteger)
            End Get
            Set
                Me("ResponsabilidadDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://wswhomo.afip.gov.ar/wsfev1/service.asmx")>  _
        Public ReadOnly Property GestionComercial_wsfev1_Service() As String
            Get
                Return CType(Me("GestionComercial_wsfev1_Service"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://wsaahomo.afip.gov.ar/ws/services/LoginCms")>  _
        Public Property UrlWsaa() As String
            Get
                Return CType(Me("UrlWsaa"),String)
            End Get
            Set
                Me("UrlWsaa") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://wswhomo.afip.gov.ar/wsfev1/service.asmx")>  _
        Public Property UrlWsfe() As String
            Get
                Return CType(Me("UrlWsfe"),String)
            End Get
            Set
                Me("UrlWsfe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("wsfe")>  _
        Public Property WsaaIdServicio() As String
            Get
                Return CType(Me("WsaaIdServicio"),String)
            End Get
            Set
                Me("WsaaIdServicio") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property WsaaProxy() As String
            Get
                Return CType(Me("WsaaProxy"),String)
            End Get
            Set
                Me("WsaaProxy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property WsaaProxyPassword() As String
            Get
                Return CType(Me("WsaaProxyPassword"),String)
            End Get
            Set
                Me("WsaaProxyPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property WsaaProxyUser() As String
            Get
                Return CType(Me("WsaaProxyUser"),String)
            End Get
            Set
                Me("WsaaProxyUser") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("c:\electronica\cert.p12")>  _
        Public Property WsaaCertificado() As String
            Get
                Return CType(Me("WsaaCertificado"),String)
            End Get
            Set
                Me("WsaaCertificado") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("13181372")>  _
        Public Property WsaaCertificadoPassword() As String
            Get
                Return CType(Me("WsaaCertificadoPassword"),String)
            End Get
            Set
                Me("WsaaCertificadoPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("c:\electronica")>  _
        Public Property WsaaRutaTicket() As String
            Get
                Return CType(Me("WsaaRutaTicket"),String)
            End Get
            Set
                Me("WsaaRutaTicket") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("c:\electronica")>  _
        Public Property WsfeRutaSalidas() As String
            Get
                Return CType(Me("WsfeRutaSalidas"),String)
            End Get
            Set
                Me("WsfeRutaSalidas") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CAJA")>  _
        Public Property CtaBancariaPredeterminada() As String
            Get
                Return CType(Me("CtaBancariaPredeterminada"),String)
            End Get
            Set
                Me("CtaBancariaPredeterminada") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("002")>  _
        Public Property CptoBancarioEgresoPredeterminado() As String
            Get
                Return CType(Me("CptoBancarioEgresoPredeterminado"),String)
            End Get
            Set
                Me("CptoBancarioEgresoPredeterminado") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("001")>  _
        Public Property CptoBancarioIngresoPredeterminado() As String
            Get
                Return CType(Me("CptoBancarioIngresoPredeterminado"),String)
            End Get
            Set
                Me("CptoBancarioIngresoPredeterminado") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Com1")>  _
        Public Property PuertoCommFiscal() As Global.EpsonFPHostControlX.TxCommPort
            Get
                Return CType(Me("PuertoCommFiscal"),Global.EpsonFPHostControlX.TxCommPort)
            End Get
            Set
                Me("PuertoCommFiscal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property CodigoConsFinal() As ULong
            Get
                Return CType(Me("CodigoConsFinal"),ULong)
            End Get
            Set
                Me("CodigoConsFinal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property PuntoVtaMayorista() As UInteger
            Get
                Return CType(Me("PuntoVtaMayorista"),UInteger)
            End Get
            Set
                Me("PuntoVtaMayorista") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property PuntoVtaMinorista() As UInteger
            Get
                Return CType(Me("PuntoVtaMinorista"),UInteger)
            End Get
            Set
                Me("PuntoVtaMinorista") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://wswhomo.afip.gov.ar/WSCDC/service.asmx")>  _
        Public ReadOnly Property GestionComercial_wscdc_Service() As String
            Get
                Return CType(Me("GestionComercial_wscdc_Service"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://wswhomo.afip.gov.ar/WSCDC/service.asmx")>  _
        Public Property UrlWscdc() As String
            Get
                Return CType(Me("UrlWscdc"),String)
            End Get
            Set
                Me("UrlWscdc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("wscdc")>  _
        Public Property WscdcIdServicio() As String
            Get
                Return CType(Me("WscdcIdServicio"),String)
            End Get
            Set
                Me("WscdcIdServicio") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("16197")>  _
        Public Property LocalidadDefault() As UInteger
            Get
                Return CType(Me("LocalidadDefault"),UInteger)
            End Get
            Set
                Me("LocalidadDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
        Public Property MaximoItemsMayorista() As Integer
            Get
                Return CType(Me("MaximoItemsMayorista"),Integer)
            End Get
            Set
                Me("MaximoItemsMayorista") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property MaximoItemsFiscal() As Integer
            Get
                Return CType(Me("MaximoItemsFiscal"),Integer)
            End Get
            Set
                Me("MaximoItemsFiscal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property MaximoItemsCompra() As Integer
            Get
                Return CType(Me("MaximoItemsCompra"),Integer)
            End Get
            Set
                Me("MaximoItemsCompra") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property PuntoVtaManual() As UInteger
            Get
                Return CType(Me("PuntoVtaManual"),UInteger)
            End Get
            Set
                Me("PuntoVtaManual") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property PuntoVtaRto() As UInteger
            Get
                Return CType(Me("PuntoVtaRto"),UInteger)
            End Get
            Set
                Me("PuntoVtaRto") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property CbteDefaultA_Fiscal() As UInteger
            Get
                Return CType(Me("CbteDefaultA_Fiscal"),UInteger)
            End Get
            Set
                Me("CbteDefaultA_Fiscal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
        Public Property CbteDefaultB_Fiscal() As UInteger
            Get
                Return CType(Me("CbteDefaultB_Fiscal"),UInteger)
            End Get
            Set
                Me("CbteDefaultB_Fiscal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("13")>  _
        Public Property IdProvinciaDefault() As UInteger
            Get
                Return CType(Me("IdProvinciaDefault"),UInteger)
            End Get
            Set
                Me("IdProvinciaDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property PuntoVtaAjustesProv() As String
            Get
                Return CType(Me("PuntoVtaAjustesProv"),String)
            End Get
            Set
                Me("PuntoVtaAjustesProv") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MailFrom() As String
            Get
                Return CType(Me("MailFrom"),String)
            End Get
            Set
                Me("MailFrom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MailSubject() As String
            Get
                Return CType(Me("MailSubject"),String)
            End Get
            Set
                Me("MailSubject") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MailMessage() As String
            Get
                Return CType(Me("MailMessage"),String)
            End Get
            Set
                Me("MailMessage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SmtpHost() As String
            Get
                Return CType(Me("SmtpHost"),String)
            End Get
            Set
                Me("SmtpHost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SmtpPort() As String
            Get
                Return CType(Me("SmtpPort"),String)
            End Get
            Set
                Me("SmtpPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SmtpUser() As String
            Get
                Return CType(Me("SmtpUser"),String)
            End Get
            Set
                Me("SmtpUser") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SmtpPassword() As String
            Get
                Return CType(Me("SmtpPassword"),String)
            End Get
            Set
                Me("SmtpPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SmtpUseSSL() As String
            Get
                Return CType(Me("SmtpUseSSL"),String)
            End Get
            Set
                Me("SmtpUseSSL") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://wswhomo.afip.gov.ar/WSCDC/service.asmx")>  _
        Public ReadOnly Property Principal_wscdc_Service() As String
            Get
                Return CType(Me("Principal_wscdc_Service"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://wswhomo.afip.gov.ar/wsfev1/service.asmx")>  _
        Public ReadOnly Property Principal_wsfev1_Service() As String
            Get
                Return CType(Me("Principal_wsfev1_Service"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property PuntoVtaPresupuesto() As String
            Get
                Return CType(Me("PuntoVtaPresupuesto"),String)
            End Get
            Set
                Me("PuntoVtaPresupuesto") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Principal.My.MySettings
            Get
                Return Global.Principal.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
